
Vagrant.configure("2") do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.vm.hostname = "control-host"

  config.vm.network :forwarded_port, guest: 22, host: 1022
  config.vm.network :forwarded_port, guest: 80, host: 1080

  config.vm.network "private_network", ip: "192.168.50.10"

  config.vm.define "ansible_ctl_vm"

  config.vm.provider "virtualbox" do |v|
    v.name = "Ansible Control host"
  end

  config.vm.provision "add_hosts_block", type: "shell", path: "add_hosts.sh"

end
